# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_sign.ui'
#
# Created: Mon Jun 13 14:08:28 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore
from PyQt4 import QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(424, 400)
        Dialog.setWindowTitle(_fromUtf8(""))
        self.front_Sign = QtGui.QTabWidget(Dialog)
        self.front_Sign.setEnabled(True)
        self.front_Sign.setGeometry(QtCore.QRect(10, 10, 401, 341))
        self.front_Sign.setDocumentMode(False)
        self.front_Sign.setMovable(True)
        self.front_Sign.setObjectName(_fromUtf8("front_Sign"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.username_login = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.username_login.setMaximumSize(QtCore.QSize(217, 27))
        self.username_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username_login.setText(_fromUtf8(""))
        self.username_login.setObjectName(_fromUtf8("username_login"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.username_login)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_22)
        self.Password_login = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.Password_login.setMaximumSize(QtCore.QSize(217, 27))
        self.Password_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_login.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.Password_login.setText(_fromUtf8(""))
        self.Password_login.setEchoMode(QtGui.QLineEdit.Password)
        self.Password_login.setObjectName(_fromUtf8("Password_login"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.Password_login)
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(190, 210, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.singup_login = QtGui.QPushButton(self.tab)
        self.singup_login.setGeometry(QtCore.QRect(280, 240, 98, 27))
        self.singup_login.setObjectName(_fromUtf8("singup_login"))
        self.Enter_login = QtGui.QCommandLinkButton(self.tab)
        self.Enter_login.setGeometry(QtCore.QRect(280, 90, 81, 31))
        self.Enter_login.setObjectName(_fromUtf8("Enter_login"))
        self.reset_login = QtGui.QCommandLinkButton(self.tab)
        self.reset_login.setGeometry(QtCore.QRect(200, 90, 81, 31))
        self.reset_login.setObjectName(_fromUtf8("reset_login"))
        self.front_Sign.addTab(self.tab, _fromUtf8(""))
        self.Form_signup = QtGui.QWidget()
        self.Form_signup.setObjectName(_fromUtf8("Form_signup"))
        self.formLayout = QtGui.QFormLayout(self.Form_signup)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_email_signup = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_email_signup.setFont(font)
        self.label_email_signup.setObjectName(_fromUtf8("label_email_signup"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_email_signup)
        self.email_sigup = QtGui.QLineEdit(self.Form_signup)
        self.email_sigup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.email_sigup.setText(_fromUtf8(""))
        self.email_sigup.setObjectName(_fromUtf8("email_sigup"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.email_sigup)
        self.label_fullname_signup_ = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_fullname_signup_.setFont(font)
        self.label_fullname_signup_.setObjectName(_fromUtf8("label_fullname_signup_"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_fullname_signup_)
        self.fullname_signup = QtGui.QLineEdit(self.Form_signup)
        self.fullname_signup.setEnabled(True)
        self.fullname_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fullname_signup.setText(_fromUtf8(""))
        self.fullname_signup.setObjectName(_fromUtf8("fullname_signup"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fullname_signup)
        self.label_username_signup = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_username_signup.setFont(font)
        self.label_username_signup.setObjectName(_fromUtf8("label_username_signup"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_username_signup)
        self.username_signup = QtGui.QLineEdit(self.Form_signup)
        self.username_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username_signup.setText(_fromUtf8(""))
        self.username_signup.setObjectName(_fromUtf8("username_signup"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.username_signup)
        self.label_password_signup = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_password_signup.setFont(font)
        self.label_password_signup.setObjectName(_fromUtf8("label_password_signup"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_password_signup)
        self.password_signup = QtGui.QLineEdit(self.Form_signup)
        self.password_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password_signup.setText(_fromUtf8(""))
        self.password_signup.setObjectName(_fromUtf8("password_signup"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.password_signup)
        self.label_address_signup = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_address_signup.setFont(font)
        self.label_address_signup.setObjectName(_fromUtf8("label_address_signup"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_address_signup)
        self.address_signup = QtGui.QLineEdit(self.Form_signup)
        self.address_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.address_signup.setText(_fromUtf8(""))
        self.address_signup.setObjectName(_fromUtf8("address_signup"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.address_signup)
        self.label_password_recovery = QtGui.QLabel(self.Form_signup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_password_recovery.setFont(font)
        self.label_password_recovery.setObjectName(_fromUtf8("label_password_recovery"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_password_recovery)
        self.answer_signup = QtGui.QLineEdit(self.Form_signup)
        self.answer_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.answer_signup.setText(_fromUtf8(""))
        self.answer_signup.setObjectName(_fromUtf8("answer_signup"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.answer_signup)
        self.accept_signup = QtGui.QDialogButtonBox(self.Form_signup)
        self.accept_signup.setMinimumSize(QtCore.QSize(0, 27))
        self.accept_signup.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.accept_signup.setObjectName(_fromUtf8("accept_signup"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.accept_signup)
        self.question_signup = QtGui.QComboBox(self.Form_signup)
        self.question_signup.setObjectName(_fromUtf8("question_signup"))
        self.question_signup.addItem(_fromUtf8(""))
        self.question_signup.addItem(_fromUtf8(""))
        self.question_signup.addItem(_fromUtf8(""))
        self.question_signup.addItem(_fromUtf8(""))
        self.question_signup.setItemText(3, _fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.question_signup)
        self.progressBar_signup = QtGui.QProgressBar(self.Form_signup)
        self.progressBar_signup.setProperty("value", 24)
        self.progressBar_signup.setObjectName(_fromUtf8("progressBar_signup"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.progressBar_signup)
        self.front_Sign.addTab(self.Form_signup, _fromUtf8("Sign Up"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.info_sign = QtGui.QPlainTextEdit(self.tab_2)
        self.info_sign.setGeometry(QtCore.QRect(5, 10, 391, 291))
        self.info_sign.setObjectName(_fromUtf8("info_sign"))
        self.front_Sign.addTab(self.tab_2, _fromUtf8(""))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(20, 350, 101, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Phetsarath OT"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(70, 380, 341, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TakaoPGothic"))
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))

        self.retranslateUi(Dialog)
        self.front_Sign.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.label_21.setText(_translate("Dialog", "Username/Email *", None))
        self.label_22.setText(_translate("Dialog", "Password *", None))
        self.label_23.setText(_translate("Dialog", "Do you need twitter Account??", None))
        self.singup_login.setText(_translate("Dialog", "Sign Up", None))
        self.Enter_login.setText(_translate("Dialog", "Enter", None))
        self.reset_login.setText(_translate("Dialog", "Reset", None))
        self.front_Sign.setTabText(self.front_Sign.indexOf(self.tab), _translate("Dialog", "Sign In", None))
        self.label_email_signup.setText(_translate("Dialog", "Email*", None))
        self.label_fullname_signup_.setText(_translate("Dialog", "Full Name*", None))
        self.label_username_signup.setText(_translate("Dialog", "Username*", None))
        self.label_password_signup.setText(_translate("Dialog", "Password*", None))
        self.label_address_signup.setText(_translate("Dialog", "Address*", None))
        self.address_signup.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_password_recovery.setText(_translate("Dialog", "Password Recovery*", None))
        self.question_signup.setItemText(0, _translate("Dialog", "Your Mother Name?", None))
        self.question_signup.setItemText(1, _translate("Dialog", "Your Birthday?", None))
        self.question_signup.setItemText(2, _translate("Dialog", "Your Father Name?", None))
        self.info_sign.setPlainText(_translate("Dialog", "## Doc. English\n"
"Before you will using the application,\n"
"you must you sign up in sign up page, after you sign up please sign In.\n"
"\n"
"##Doc. Indonesia\n"
"Sebelum anda akan menggunakan aplikasi, kamu harus mendatarkan diri, setelah mendaftarkan diri silahkan login.\n"
"\n"
"##Doc. Lombok - Indonesia\n"
"Sebelum side ngadu aplikasi ine, silaq daftar juluk, terus baruq side login. \n"
" \n"
"", None))
        self.front_Sign.setTabText(self.front_Sign.indexOf(self.tab_2), _translate("Dialog", "How to use", None))
        self.label_20.setText(_translate("Dialog", "nb * = field required ", None))
        self.label_24.setText(_translate("Dialog", "Copyright @ 2016 by juandisay.All Rights Reserved | Powered By Open Source", None))
        self.label_3.setText(_translate("Dialog", "Welcome PySocial Magic v.0.beta", None))